# Generated by Django 3.0.7 on 2020-07-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wife_name', models.CharField(max_length=100)),
                ('wife_dob', models.DateTimeField()),
                ('wife_bornPlace', models.CharField(max_length=500)),
                ('wife_occupation', models.TextField()),
                ('wife_email', models.EmailField(max_length=254)),
                ('wife_deceasedDate', models.DateTimeField()),
                ('husband_name', models.CharField(max_length=100)),
                ('husband_dob', models.DateTimeField()),
                ('husband_bornPlace', models.CharField(max_length=500)),
                ('husband_occupation', models.TextField()),
                ('husband_email', models.EmailField(max_length=254)),
                ('husband_deceasedDate', models.DateTimeField()),
                ('parent_id', models.IntegerField()),
            ],
        ),
    ]
