# Generated by Django 3.0.7 on 2020-07-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='husband_dob',
            field=models.DateTimeField(verbose_name=['%m/%d/%Y']),
        ),
        migrations.AlterField(
            model_name='couple',
            name='wife_dob',
            field=models.DateTimeField(verbose_name=['%m/%d/%Y']),
        ),
    ]
