# Generated by Django 3.0.7 on 2020-07-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_auto_20200701_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='husband_deceasedDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='couple',
            name='husband_dob',
            field=models.DateField(verbose_name=['%m/%d/%Y']),
        ),
        migrations.AlterField(
            model_name='couple',
            name='wife_deceasedDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='couple',
            name='wife_dob',
            field=models.DateField(verbose_name=['%m/%d/%Y']),
        ),
    ]
